version: '3'
services:
  test:
    image: golang:1.21-alpine
    volumes:
      - ./:/logrus-postgres-hook
    working_dir: /logrus-postgres-hook
    command: sh -c "go mod tidy && go install github.com/rakyll/gotest@latest && gotest -v -p 1 ./... -cover"
    depends_on:
      - postgres
  postgres:
    image: postgres:9-alpine
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=gigasecret
    ports:
      - 5432:5432
